name: weeklyreport

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip install requests

      - name: run
        env:
          OPEN_CLOUD_API_KEY: ${{ secrets.OPEN_CLOUD_API_KEY }}
          ID: ${{ secrets.ID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python weeklyreport.py
